//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1405.0 using the following command:
// xscgen -n =CiscoIPPhone --nullable --collectionType System.Collections.Generic.List`1 -o out CiscoIPPhone.xsd
namespace CiscoIPPhone
{
    
    
    /// <summary>
    /// <para>Width mode for supported XSI application windows. Normal is the default; Wide uses the full supported screen width.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Width mode for supported XSI application windows. Normal is the default; Wide use" +
        "s the full supported screen width."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneWindowModeType", Namespace="")]
    public enum CiscoIpPhoneWindowModeType
    {
        
        Normal,
        
        Wide,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneExecuteItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneExecuteItemType
    {
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedByte; minInclusive=0, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedByte; minInclusive=0, maxInclusive=2" +
            ". Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("Priority")]
        public byte PriorityValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Priority property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PriorityValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedByte; minInclusive=0, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<byte> Priority
        {
            get
            {
                if (this.PriorityValueSpecified)
                {
                    return this.PriorityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PriorityValue = value.GetValueOrDefault();
                this.PriorityValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlAttributeAttribute("URL")]
        public string Url { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneResponseItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneResponseItemType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public short Status { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public string Data { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneTouchAreaMenuItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneTouchAreaMenuItemType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TouchArea")]
        public CiscoIpPhoneTouchAreaType TouchArea { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneTouchAreaType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneTouchAreaType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("X1")]
        public ushort X1 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Y1")]
        public ushort Y1 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("X2")]
        public ushort X2 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Y2")]
        public ushort Y2 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneDirectoryEntryType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneDirectoryEntryType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Telephone")]
        public string Telephone { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneInputItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneInputItemType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("DisplayName")]
        public string DisplayName { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("QueryStringParam")]
        public string QueryStringParam { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("InputFlags")]
        public CiscoIpPhoneInputItemTypeInputFlags InputFlags { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("DefaultValue")]
        public string DefaultValue { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIpPhoneInputItemTypeInputFlags", Namespace="", AnonymousType=true)]
    public enum CiscoIpPhoneInputItemTypeInputFlags
    {
        
        A,
        
        T,
        
        N,
        
        E,
        
        U,
        
        L,
        
        [System.Xml.Serialization.XmlEnumAttribute("AP")]
        Ap,
        
        [System.Xml.Serialization.XmlEnumAttribute("TP")]
        Tp,
        
        [System.Xml.Serialization.XmlEnumAttribute("NP")]
        Np,
        
        [System.Xml.Serialization.XmlEnumAttribute("EP")]
        Ep,
        
        [System.Xml.Serialization.XmlEnumAttribute("UP")]
        Up,
        
        [System.Xml.Serialization.XmlEnumAttribute("LP")]
        Lp,
        
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        Pa,
        
        [System.Xml.Serialization.XmlEnumAttribute("PT")]
        Pt,
        
        [System.Xml.Serialization.XmlEnumAttribute("PN")]
        Pn,
        
        [System.Xml.Serialization.XmlEnumAttribute("PE")]
        Pe,
        
        [System.Xml.Serialization.XmlEnumAttribute("PU")]
        Pu,
        
        [System.Xml.Serialization.XmlEnumAttribute("PL")]
        Pl,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneMenuItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneMenuItemType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(64)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneIconItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneIconItemType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Index")]
        public ushort Index { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=16. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "16. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Width")]
        public ushort Width { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=10. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "10. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Height")]
        public ushort Height { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "2. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Depth")]
        public ushort Depth { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(40)]
        [System.Xml.Serialization.XmlElementAttribute("Data", DataType="hexBinary")]
        public byte[] Data { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneIconMenuItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneIconMenuItemType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(64)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=0, maxInclusive=9. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=0, maxInclusive=9. Flatt" +
            "ened to built-in type for Go code generation."))]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("IconIndex")]
        public short IconIndexValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IconIndex property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IconIndexValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=0, maxInclusive=9. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<short> IconIndex
        {
            get
            {
                if (this.IconIndexValueSpecified)
                {
                    return this.IconIndexValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IconIndexValue = value.GetValueOrDefault();
                this.IconIndexValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneIconFileItemType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneIconFileItemType
    {
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=0, maxInclusive=9. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=0, maxInclusive=" +
            "9. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Index")]
        public ushort Index { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneKeyType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneKeyType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Key")]
        public CiscoIpPhoneKeyTypeKey Key { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URLDown")]
        public string UrlDown { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIpPhoneKeyTypeKey", Namespace="", AnonymousType=true)]
    public enum CiscoIpPhoneKeyTypeKey
    {
        
        KeyPad0,
        
        KeyPad1,
        
        KeyPad2,
        
        KeyPad3,
        
        KeyPad4,
        
        KeyPad5,
        
        KeyPad6,
        
        KeyPad7,
        
        KeyPad8,
        
        KeyPad9,
        
        KeyPadStar,
        
        KeyPadPound,
        
        NavUp,
        
        NavDown,
        
        NavLeft,
        
        NavRight,
        
        NavSelect,
        
        NavBack,
        
        PushToTalk,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneSoftKeyType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CiscoIpPhoneSoftKeyType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=8. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "8. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public ushort Position { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlElementAttribute("URLDown")]
        public string UrlDown { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneDisplayableType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneDirectory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneGraphicFileMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneGraphicMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneIconFileMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneIconMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneImage))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneImageFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneMenu))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CiscoIpPhoneText))]
    public partial class CiscoIpPhoneDisplayableType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Prompt")]
        public string Prompt { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneSoftKeyType> _softKeyItem;
        
        [System.Xml.Serialization.XmlElementAttribute("SoftKeyItem")]
        public System.Collections.Generic.List<CiscoIpPhoneSoftKeyType> SoftKeyItem
        {
            get
            {
                return _softKeyItem;
            }
            private set
            {
                _softKeyItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SoftKeyItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SoftKeyItemSpecified
        {
            get
            {
                return (this.SoftKeyItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneDisplayableType" /> class.</para>
        /// </summary>
        public CiscoIpPhoneDisplayableType()
        {
            this._softKeyItem = new System.Collections.Generic.List<CiscoIpPhoneSoftKeyType>();
            this._keyItem = new System.Collections.Generic.List<CiscoIpPhoneKeyType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneKeyType> _keyItem;
        
        [System.Xml.Serialization.XmlElementAttribute("KeyItem")]
        public System.Collections.Generic.List<CiscoIpPhoneKeyType> KeyItem
        {
            get
            {
                return _keyItem;
            }
            private set
            {
                _keyItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the KeyItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeyItemSpecified
        {
            get
            {
                return (this.KeyItem.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CiscoIpPhoneDisplayableTypeKeypadTarget _keypadTarget = CiscoIPPhone.CiscoIpPhoneDisplayableTypeKeypadTarget.Application;
        
        [System.ComponentModel.DefaultValueAttribute(CiscoIPPhone.CiscoIpPhoneDisplayableTypeKeypadTarget.Application)]
        [System.Xml.Serialization.XmlAttributeAttribute("keypadTarget")]
        public CiscoIpPhoneDisplayableTypeKeypadTarget KeypadTarget
        {
            get
            {
                return _keypadTarget;
            }
            set
            {
                _keypadTarget = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 64.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(64)]
        [System.Xml.Serialization.XmlAttributeAttribute("appId")]
        public string AppId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlAttributeAttribute("onAppFocusLost")]
        public string OnAppFocusLost { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlAttributeAttribute("onAppFocusGained")]
        public string OnAppFocusGained { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlAttributeAttribute("onAppMinimized")]
        public string OnAppMinimized { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.Xml.Serialization.XmlAttributeAttribute("onAppClosed")]
        public string OnAppClosed { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIpPhoneDisplayableTypeKeypadTarget", Namespace="", AnonymousType=true)]
    public enum CiscoIpPhoneDisplayableTypeKeypadTarget
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("application")]
        Application,
        
        [System.Xml.Serialization.XmlEnumAttribute("applicationCall")]
        ApplicationCall,
        
        [System.Xml.Serialization.XmlEnumAttribute("activeCall")]
        ActiveCall,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneExecute", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneExecute", Namespace="")]
    public partial class CiscoIpPhoneExecute
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneExecuteItemType> _executeItem;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExecuteItem")]
        public System.Collections.Generic.List<CiscoIpPhoneExecuteItemType> ExecuteItem
        {
            get
            {
                return _executeItem;
            }
            private set
            {
                _executeItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneExecute" /> class.</para>
        /// </summary>
        public CiscoIpPhoneExecute()
        {
            this._executeItem = new System.Collections.Generic.List<CiscoIpPhoneExecuteItemType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPhoneResponse", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPhoneResponse", Namespace="")]
    public partial class CiscoIPhoneResponse
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneResponseItemType> _responseItem;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ResponseItem")]
        public System.Collections.Generic.List<CiscoIpPhoneResponseItemType> ResponseItem
        {
            get
            {
                return _responseItem;
            }
            private set
            {
                _responseItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIPhoneResponse" /> class.</para>
        /// </summary>
        public CiscoIPhoneResponse()
        {
            this._responseItem = new System.Collections.Generic.List<CiscoIpPhoneResponseItemType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneError", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneError", Namespace="")]
    public partial class CiscoIpPhoneError
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Number")]
        public ushort Number { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneText", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneText", Namespace="")]
    public partial class CiscoIpPhoneText : CiscoIpPhoneDisplayableType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 4000.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(4000)]
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public string Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneInput", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneInput", Namespace="")]
    public partial class CiscoIpPhoneInput : CiscoIpPhoneDisplayableType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneInputItemType> _inputItem;
        
        [System.Xml.Serialization.XmlElementAttribute("InputItem")]
        public System.Collections.Generic.List<CiscoIpPhoneInputItemType> InputItem
        {
            get
            {
                return _inputItem;
            }
            private set
            {
                _inputItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the InputItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InputItemSpecified
        {
            get
            {
                return (this.InputItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneInput" /> class.</para>
        /// </summary>
        public CiscoIpPhoneInput()
        {
            this._inputItem = new System.Collections.Generic.List<CiscoIpPhoneInputItemType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneDirectory", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneDirectory", Namespace="")]
    public partial class CiscoIpPhoneDirectory : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneDirectoryEntryType> _directoryEntry;
        
        [System.Xml.Serialization.XmlElementAttribute("DirectoryEntry")]
        public System.Collections.Generic.List<CiscoIpPhoneDirectoryEntryType> DirectoryEntry
        {
            get
            {
                return _directoryEntry;
            }
            private set
            {
                _directoryEntry = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DirectoryEntry collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectoryEntrySpecified
        {
            get
            {
                return (this.DirectoryEntry.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneDirectory" /> class.</para>
        /// </summary>
        public CiscoIpPhoneDirectory()
        {
            this._directoryEntry = new System.Collections.Generic.List<CiscoIpPhoneDirectoryEntryType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneImage", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneImage", Namespace="")]
    public partial class CiscoIpPhoneImage : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=132. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=132. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=64. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=64. Fla" +
            "ttened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=133. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "133. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Width")]
        public ushort Width { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=65. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "65. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Height")]
        public ushort Height { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "2. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Depth")]
        public ushort Depth { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 2162.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2162)]
        [System.Xml.Serialization.XmlElementAttribute("Data", DataType="hexBinary")]
        public byte[] Data { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CiscoIpPhoneWindowModeType _windowMode = CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal;
        
        [System.ComponentModel.DefaultValueAttribute(CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal)]
        [System.Xml.Serialization.XmlAttributeAttribute("WindowMode")]
        public CiscoIpPhoneWindowModeType WindowMode
        {
            get
            {
                return _windowMode;
            }
            set
            {
                _windowMode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneImageFile", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneImageFile", Namespace="")]
    public partial class CiscoIpPhoneImageFile : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=297. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=297. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=167. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=167. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CiscoIpPhoneWindowModeType _windowMode = CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal;
        
        [System.ComponentModel.DefaultValueAttribute(CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal)]
        [System.Xml.Serialization.XmlAttributeAttribute("WindowMode")]
        public CiscoIpPhoneWindowModeType WindowMode
        {
            get
            {
                return _windowMode;
            }
            set
            {
                _windowMode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneMenu", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneMenu", Namespace="")]
    public partial class CiscoIpPhoneMenu : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneMenuItemType> _menuItem;
        
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public System.Collections.Generic.List<CiscoIpPhoneMenuItemType> MenuItem
        {
            get
            {
                return _menuItem;
            }
            private set
            {
                _menuItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MenuItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemSpecified
        {
            get
            {
                return (this.MenuItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneMenu" /> class.</para>
        /// </summary>
        public CiscoIpPhoneMenu()
        {
            this._menuItem = new System.Collections.Generic.List<CiscoIpPhoneMenuItemType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneIconMenu", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneIconMenu", Namespace="")]
    public partial class CiscoIpPhoneIconMenu : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType> _menuItem;
        
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType> MenuItem
        {
            get
            {
                return _menuItem;
            }
            private set
            {
                _menuItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MenuItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemSpecified
        {
            get
            {
                return (this.MenuItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneIconMenu" /> class.</para>
        /// </summary>
        public CiscoIpPhoneIconMenu()
        {
            this._menuItem = new System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType>();
            this._iconItem = new System.Collections.Generic.List<CiscoIpPhoneIconItemType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneIconItemType> _iconItem;
        
        [System.Xml.Serialization.XmlElementAttribute("IconItem")]
        public System.Collections.Generic.List<CiscoIpPhoneIconItemType> IconItem
        {
            get
            {
                return _iconItem;
            }
            private set
            {
                _iconItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IconItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IconItemSpecified
        {
            get
            {
                return (this.IconItem.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneIconFileMenu", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneIconFileMenu", Namespace="")]
    public partial class CiscoIpPhoneIconFileMenu : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType> _menuItem;
        
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType> MenuItem
        {
            get
            {
                return _menuItem;
            }
            private set
            {
                _menuItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MenuItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemSpecified
        {
            get
            {
                return (this.MenuItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneIconFileMenu" /> class.</para>
        /// </summary>
        public CiscoIpPhoneIconFileMenu()
        {
            this._menuItem = new System.Collections.Generic.List<CiscoIpPhoneIconMenuItemType>();
            this._iconItem = new System.Collections.Generic.List<CiscoIpPhoneIconFileItemType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneIconFileItemType> _iconItem;
        
        [System.Xml.Serialization.XmlElementAttribute("IconItem")]
        public System.Collections.Generic.List<CiscoIpPhoneIconFileItemType> IconItem
        {
            get
            {
                return _iconItem;
            }
            private set
            {
                _iconItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IconItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IconItemSpecified
        {
            get
            {
                return (this.IconItem.Count != 0);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IconIndex")]
        public ushort IconIndexValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IconIndex property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IconIndexValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ushort> IconIndex
        {
            get
            {
                if (this.IconIndexValueSpecified)
                {
                    return this.IconIndexValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IconIndexValue = value.GetValueOrDefault();
                this.IconIndexValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneGraphicMenu", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneGraphicMenu", Namespace="")]
    public partial class CiscoIpPhoneGraphicMenu : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=132. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=132. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=64. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=64. Fla" +
            "ttened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=133. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "133. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Width")]
        public ushort Width { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=65. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "65. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Height")]
        public ushort Height { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "2. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Depth")]
        public ushort Depth { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 2162.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2162)]
        [System.Xml.Serialization.XmlElementAttribute("Data", DataType="hexBinary")]
        public byte[] Data { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneMenuItemType> _menuItem;
        
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public System.Collections.Generic.List<CiscoIpPhoneMenuItemType> MenuItem
        {
            get
            {
                return _menuItem;
            }
            private set
            {
                _menuItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MenuItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemSpecified
        {
            get
            {
                return (this.MenuItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneGraphicMenu" /> class.</para>
        /// </summary>
        public CiscoIpPhoneGraphicMenu()
        {
            this._menuItem = new System.Collections.Generic.List<CiscoIpPhoneMenuItemType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CiscoIpPhoneWindowModeType _windowMode = CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal;
        
        [System.ComponentModel.DefaultValueAttribute(CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal)]
        [System.Xml.Serialization.XmlAttributeAttribute("WindowMode")]
        public CiscoIpPhoneWindowModeType WindowMode
        {
            get
            {
                return _windowMode;
            }
            set
            {
                _windowMode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneGraphicFileMenu", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneGraphicFileMenu", Namespace="")]
    public partial class CiscoIpPhoneGraphicFileMenu : CiscoIpPhoneDisplayableType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=297. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=297. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=167. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=167. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CiscoIpPhoneTouchAreaMenuItemType> _menuItem;
        
        [System.Xml.Serialization.XmlElementAttribute("MenuItem")]
        public System.Collections.Generic.List<CiscoIpPhoneTouchAreaMenuItemType> MenuItem
        {
            get
            {
                return _menuItem;
            }
            private set
            {
                _menuItem = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MenuItem collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MenuItemSpecified
        {
            get
            {
                return (this.MenuItem.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CiscoIpPhoneGraphicFileMenu" /> class.</para>
        /// </summary>
        public CiscoIpPhoneGraphicFileMenu()
        {
            this._menuItem = new System.Collections.Generic.List<CiscoIpPhoneTouchAreaMenuItemType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CiscoIpPhoneWindowModeType _windowMode = CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal;
        
        [System.ComponentModel.DefaultValueAttribute(CiscoIPPhone.CiscoIpPhoneWindowModeType.Normal)]
        [System.Xml.Serialization.XmlAttributeAttribute("WindowMode")]
        public CiscoIpPhoneWindowModeType WindowMode
        {
            get
            {
                return _windowMode;
            }
            set
            {
                _windowMode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneStatus", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneStatus", Namespace="")]
    public partial class CiscoIpPhoneStatus
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public string Text { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to " +
            "built-in type for Go code generation."))]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Timer")]
        public ushort TimerValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Timer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TimerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ushort> Timer
        {
            get
            {
                if (this.TimerValueSpecified)
                {
                    return this.TimerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TimerValue = value.GetValueOrDefault();
                this.TimerValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=105. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=105. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=20. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=20. Fla" +
            "ttened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=106. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "106. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Width")]
        public ushort Width { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=21. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "21. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Height")]
        public ushort Height { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=2. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=1, maxInclusive=" +
            "2. Flattened to built-in type for Go code generation."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Depth")]
        public ushort Depth { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 557.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(557)]
        [System.Xml.Serialization.XmlElementAttribute("Data", DataType="hexBinary")]
        public byte[] Data { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1405.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CiscoIPPhoneStatusFile", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CiscoIPPhoneStatusFile", Namespace="")]
    public partial class CiscoIpPhoneStatusFile
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 32.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(32)]
        [System.Xml.Serialization.XmlElementAttribute("Text")]
        public string Text { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to " +
            "built-in type for Go code generation."))]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("Timer")]
        public ushort TimerValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Timer property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TimerValueSpecified { get; set; }
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:unsignedShort; minInclusive=0. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ushort> Timer
        {
            get
            {
                if (this.TimerValueSpecified)
                {
                    return this.TimerValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TimerValue = value.GetValueOrDefault();
                this.TimerValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationX = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=261. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=261. Fl" +
            "attened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationX")]
        public short LocationX
        {
            get
            {
                return _locationX;
            }
            set
            {
                _locationX = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private short _locationY = 0;
        
        /// <summary>
        /// <para>Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=49. Flattened to built-in type for Go code generation.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.ComponentModel.DescriptionAttribute(("Cisco original restriction: base=xsd:short; minInclusive=-1, maxInclusive=49. Fla" +
            "ttened to built-in type for Go code generation."))]
        [System.Xml.Serialization.XmlElementAttribute("LocationY")]
        public short LocationY
        {
            get
            {
                return _locationY;
            }
            set
            {
                _locationY = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 256.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(256)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("URL")]
        public string Url { get; set; }
    }
}
